## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

ticker = 'MSFT' 
data = pd.DataFrame()
data[ticker] = wb.DataReader(ticker, data_source='yahoo', start='2000-1-1')['Adj Close']

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([ -7.47125266e-05])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([ 0.01963477])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[ 0.98713848,  1.00550982,  0.99199161, ...,  0.98718366,
         0.98274992,  0.98962503],
       [ 0.99512182,  1.00417232,  0.98840245, ...,  0.99001035,
         0.99893862,  0.98495192],
       [ 0.97323677,  0.97824105,  0.96048068, ...,  1.0103994 ,
         0.99519223,  0.99621534],
       ..., 
       [ 0.96325351,  0.99255021,  1.00943932, ...,  0.99013778,
         0.98372179,  0.98866592],
       [ 1.0062446 ,  1.00668481,  1.0047767 , ...,  0.99428712,
         0.9686699 ,  1.00849504],
       [ 0.99109268,  0.99527188,  0.9948989 , ...,  0.98479256,
         0.98811965,  0.99687317]])